In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/competitions.json"
competitions = pd.read_json(url)

competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [4]:
competitions["competition_name"].unique()

<StringArray>
[          '1. Bundesliga',  'African Cup of Nations',
        'Champions League',            'Copa America',
            'Copa del Rey', 'FA Women's Super League',
      'FIFA U20 World Cup',          'FIFA World Cup',
       'Frauen Bundesliga',     'Indian Super league',
                 'La Liga',                  'Liga F',
        'Liga Profesional',                 'Ligue 1',
     'Major League Soccer',   'North American League',
                    'NWSL',          'Premier League',
                 'Serie A',           'Serie A Women',
               'UEFA Euro',      'UEFA Europa League',
       'UEFA Women's Euro',       'Women's World Cup']
Length: 24, dtype: str

In [5]:
competitions[competitions["competition_name"] == "FIFA World Cup"]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
30,43,106,International,FIFA World Cup,male,False,True,2022,2026-05-04T01:48:57.914346,2026-05-04T01:53:40.309717,2026-05-04T01:53:40.309717,2026-05-04T01:48:57.914346
31,43,3,International,FIFA World Cup,male,False,True,2018,2026-05-15T15:48:12.789440,2021-06-13T16:17:31.694,NaN,2026-05-15T15:48:12.789440
32,43,55,International,FIFA World Cup,male,False,True,1990,2023-06-28T10:58:20.137929,2021-06-12T16:17:31.694,NaN,2023-06-28T10:58:20.137929
33,43,54,International,FIFA World Cup,male,False,True,1986,2026-05-04T01:30:23.212111,2021-06-13T16:17:31.694,NaN,2026-05-04T01:30:23.212111
34,43,51,International,FIFA World Cup,male,False,True,1974,2026-05-15T02:20:43.439689,2021-06-13T16:17:31.694,NaN,2026-05-15T02:20:43.439689
35,43,272,International,FIFA World Cup,male,False,True,1970,2026-05-04T02:09:10.916859,NaN,NaN,2026-05-04T02:09:10.916859
36,43,270,International,FIFA World Cup,male,False,True,1962,2026-05-04T02:05:35.653887,NaN,NaN,2026-05-04T02:05:35.653887
37,43,269,International,FIFA World Cup,male,False,True,1958,2026-05-04T02:02:41.853159,NaN,NaN,2026-05-04T02:02:41.853159

In [6]:
matches_url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/matches/43/106.json"
matches = pd.read_json(matches_url)
matches.shape

(64, 18)

In [7]:
matches.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'metadata',
       'match_week', 'competition_stage', 'stadium', 'referee'],
      dtype='str')

In [8]:
matches[["match_id", "match_date", "home_team", "away_team", "home_score", "away_score"]].head()

,match_id,match_date,home_team,away_team,home_score,away_score
0,3857276,2022-12-01,"{'home_team_id': 1833, 'home_team_name': 'Cana...","{'away_team_id': 788, 'away_team_name': 'Moroc...",1,2
1,3857271,2022-11-21,"{'home_team_id': 768, 'home_team_name': 'Engla...","{'away_team_id': 797, 'away_team_name': 'Iran'...",6,2
2,3857296,2022-12-01,"{'home_team_id': 785, 'home_team_name': 'Croat...","{'away_team_id': 782, 'away_team_name': 'Belgi...",0,0
3,3857274,2022-11-25,"{'home_team_id': 941, 'home_team_name': 'Nethe...","{'away_team_id': 3565, 'away_team_name': 'Ecua...",1,1
4,3857255,2022-12-01,"{'home_team_id': 778, 'home_team_name': 'Japan...","{'away_team_id': 772, 'away_team_name': 'Spain...",2,1

In [10]:
pd.json_normalize(matches["home_team"])

,home_team_id,home_team_name,home_team_gender,home_team_group,managers,country.id,country.name
0,1833,Canada,male,F,"[{'id': 4435, 'name': 'John Herdman', 'nicknam...",40,Canada
1,768,England,male,B,"[{'id': 277, 'name': 'Gareth Southgate', 'nick...",68,England
2,785,Croatia,male,F,"[{'id': 307, 'name': 'Zlatko Dalić', 'nickname...",56,Croatia
3,941,Netherlands,male,A,"[{'id': 788, 'name': 'Louis van Gaal', 'nickna...",160,Netherlands
4,778,Japan,male,E,"[{'id': 5699, 'name': 'Hajime Moriyasu', 'nick...",114,Japan
...,...,...,...,...,...,...,...
59,772,Spain,male,E,"[{'id': 793, 'name': 'Luis Enrique Martínez Ga...",214,Spain
60,785,Croatia,male,F,"[{'id': 307, 'name': 'Zlatko Dalić', 'nickname...",56,Croatia
61,2722,Cameroon,male,G,"[{'id': 1001250, 'name': 'Rigobert Song Bahana...",39,Cameroon
62,771,France,male,D,"[{'id': 545, 'name': 'Didier Deschamps', 'nick...",78,France
63,791,South Korea,male,H,"[{'id': 5688, 'name': 'Paulo Jorge Gomes Bento...",121,Korea (South)

In [11]:
events_url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/3857276.json"
events = pd.read_json(events_url)
events.shape

(3388, 38)

In [12]:
events["type_name"] = pd.json_normalize(events["type"])["name"]
events["type_name"].value_counts()

type_name
Pass                 955
Ball Receipt*        868
Carry                782
Pressure             289
Ball Recovery         93
Duel                  63
Clearance             41
Dribble               39
Miscontrol            32
Foul Committed        31
Foul Won              31
Block                 27
Dispossessed          23
Dribbled Past         23
Interception          23
Goal Keeper           16
Shot                  12
Substitution          10
Tactical Shift         5
Half Start             4
Half End               4
Injury Stoppage        4
Referee Ball-Drop      4
Starting XI            2
50/50                  2
Error                  1
Shield                 1
Own Goal For           1
Own Goal Against       1
Offside                1
Name: count, dtype: int64

In [13]:
shots = events[events["type_name"] == "Shot"]
shots.shape

(12, 39)

In [14]:
shots["shot"].iloc[0]

{'statsbomb_xg': 0.038882375000000004,
 'end_location': [104.1, 39.4],
 'key_pass_id': 'adb7af16-6e6c-4f23-a405-e9488608b93b',
 'technique': {'id': 93, 'name': 'Normal'},
 'body_part': {'id': 38, 'name': 'Left Foot'},
 'type': {'id': 87, 'name': 'Open Play'},
 'outcome': {'id': 96, 'name': 'Blocked'},
 'first_time': True,
 'freeze_frame': [{'location': [108.6, 34.8],
   'player': {'id': 9922, 'name': 'David Junior Hoilett'},
   'position': {'id': 19, 'name': 'Center Attacking Midfield'},
   'teammate': True},
  {'location': [112.7, 45.5],
   'player': {'id': 16459, 'name': 'Cyle Larin'},
   'position': {'id': 23, 'name': 'Center Forward'},
   'teammate': True},
  {'location': [108.6, 42.5],
   'player': {'id': 12770, 'name': 'Jonathan Osorio'},
   'position': {'id': 9, 'name': 'Right Defensive Midfield'},
   'teammate': True},
  {'location': [109.2, 27.6],
   'player': {'id': 24024, 'name': 'Tajon Buchanan'},
   'position': {'id': 16, 'name': 'Left Midfield'},
   'teammate': True},
  {'location': [94.4, 20.6],
   'player': {'id': 29758, 'name': 'Sam Adekugbe'},
   'position': {'id': 6, 'name': 'Left Back'},
   'teammate': True},
  {'location': [100.1, 49.5],
   'player': {'id': 12365, 'name': 'Alphonso Davies'},
   'position': {'id': 12, 'name': 'Right Midfield'},
   'teammate': True},
  {'location': [89.8, 57.6],
   'player': {'id': 44703, 'name': 'Alistair Johnston'},
   'position': {'id': 2, 'name': 'Right Back'},
   'teammate': True},
  {'location': [83.9, 46.1],
   'player': {'id': 11846, 'name': 'Steven de Sousa Vitoria'},
   'position': {'id': 3, 'name': 'Right Center Back'},
   'teammate': True},
  {'location': [108.3, 47.9],
   'player': {'id': 15890, 'name': 'Noussair Mazraoui'},
   'position': {'id': 6, 'name': 'Left Back'},
   'teammate': False},
  {'location': [112.5, 41.6],
   'player': {'id': 5234, 'name': 'Sofyan Amrabat'},
   'position': {'id': 10, 'name': 'Center Defensive Midfield'},
   'teammate': False},
  {'location': [102.2, 46.3],
   'player': {'id': 5219, 'name': 'Romain Saïss'},
   'position': {'id': 5, 'name': 'Left Center Back'},
   'teammate': False},
  {'location': [108.2, 36.6],
   'player': {'id': 12149, 'name': 'Nayef Aguerd'},
   'position': {'id': 3, 'name': 'Right Center Back'},
   'teammate': False},
  {'location': [108.9, 32.3],
   'player': {'id': 5245, 'name': 'Achraf Hakimi Mouh'},
   'position': {'id': 2, 'name': 'Right Back'},
   'teammate': False},
  {'location': [104.1, 39.3],
   'player': {'id': 46258, 'name': 'Azzedine Ounahi'},
   'position': {'id': 13, 'name': 'Right Center Midfield'},
   'teammate': False},
  {'location': [102.0, 43.2],
   'player': {'id': 3634, 'name': 'Abdelhamid Sabiri'},
   'position': {'id': 15, 'name': 'Left Center Midfield'},
   'teammate': False},
  {'location': [100.7, 52.2],
   'player': {'id': 3625, 'name': 'Sofiane Boufal'},
   'position': {'id': 21, 'name': 'Left Wing'},
   'teammate': False},
  {'location': [97.1, 38.4],
   'player': {'id': 5237, 'name': 'Hakim Ziyech'},
   'position': {'id': 17, 'name': 'Right Wing'},
   'teammate': False},
  {'location': [95.6, 41.2],
   'player': {'id': 6301, 'name': 'Youssef En-Nesyri'},
   'position': {'id': 23, 'name': 'Center Forward'},
   'teammate': False},
  {'location': [118.5, 39.1],
   'player': {'id': 6785, 'name': 'Yassine Bounou'},
   'position': {'id': 1, 'name': 'Goalkeeper'},
   'teammate': False}]}

In [15]:
shots_clean = pd.json_normalize(shots["shot"])
shots_clean[["statsbomb_xg", "body_part.name", "type.name", "outcome.name"]]

      statsbomb_xg body_part.name  type.name outcome.name
99        0.038882      Left Foot  Open Play      Blocked
202       0.024477      Left Foot  Open Play         Goal
297       0.022070     Right Foot  Free Kick      Blocked
305       0.061586      Left Foot  Open Play      Wayward
481       0.279145     Right Foot  Open Play        Off T
519       0.022624      Left Foot  Open Play        Off T
844       0.104058     Right Foot  Open Play         Goal
1188      0.097118     Right Foot  Open Play      Blocked
1640      0.094470     Right Foot  Open Play      Wayward
2273      0.051904      Left Foot  Open Play        Off T
2740      0.086874           Head  Open Play         Post
2744      0.638813           Head  Open Play        Off T