In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/competitions.json"
competitions = pd.read_json(url)

competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [2]:
competitions["competition_name"].unique()

<StringArray>
[          '1. Bundesliga',  'African Cup of Nations',
        'Champions League',            'Copa America',
            'Copa del Rey', 'FA Women's Super League',
      'FIFA U20 World Cup',          'FIFA World Cup',
       'Frauen Bundesliga',     'Indian Super league',
                 'La Liga',                  'Liga F',
        'Liga Profesional',                 'Ligue 1',
     'Major League Soccer',   'North American League',
                    'NWSL',          'Premier League',
                 'Serie A',           'Serie A Women',
               'UEFA Euro',      'UEFA Europa League',
       'UEFA Women's Euro',       'Women's World Cup']
Length: 24, dtype: str

In [3]:
competitions[competitions["competition_name"] == "FIFA World Cup"]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
30,43,106,International,FIFA World Cup,male,False,True,2022,2026-05-04T01:48:57.914346,2026-05-04T01:53:40.309717,2026-05-04T01:53:40.309717,2026-05-04T01:48:57.914346
31,43,3,International,FIFA World Cup,male,False,True,2018,2026-05-15T15:48:12.789440,2021-06-13T16:17:31.694,NaN,2026-05-15T15:48:12.789440
32,43,55,International,FIFA World Cup,male,False,True,1990,2023-06-28T10:58:20.137929,2021-06-12T16:17:31.694,NaN,2023-06-28T10:58:20.137929
33,43,54,International,FIFA World Cup,male,False,True,1986,2026-05-04T01:30:23.212111,2021-06-13T16:17:31.694,NaN,2026-05-04T01:30:23.212111
34,43,51,International,FIFA World Cup,male,False,True,1974,2026-05-15T02:20:43.439689,2021-06-13T16:17:31.694,NaN,2026-05-15T02:20:43.439689
35,43,272,International,FIFA World Cup,male,False,True,1970,2026-05-04T02:09:10.916859,NaN,NaN,2026-05-04T02:09:10.916859
36,43,270,International,FIFA World Cup,male,False,True,1962,2026-05-04T02:05:35.653887,NaN,NaN,2026-05-04T02:05:35.653887
37,43,269,International,FIFA World Cup,male,False,True,1958,2026-05-04T02:02:41.853159,NaN,NaN,2026-05-04T02:02:41.853159

In [4]:
matches_url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/matches/43/106.json"
matches = pd.read_json(matches_url)
matches.shape

(64, 18)

In [5]:
matches.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'metadata',
       'match_week', 'competition_stage', 'stadium', 'referee'],
      dtype='str')

In [6]:
matches[["match_id", "match_date", "home_team", "away_team", "home_score", "away_score"]].head()

,match_id,match_date,home_team,away_team,home_score,away_score
0,3857276,2022-12-01,"{'home_team_id': 1833, 'home_team_name': 'Cana...","{'away_team_id': 788, 'away_team_name': 'Moroc...",1,2
1,3857271,2022-11-21,"{'home_team_id': 768, 'home_team_name': 'Engla...","{'away_team_id': 797, 'away_team_name': 'Iran'...",6,2
2,3857296,2022-12-01,"{'home_team_id': 785, 'home_team_name': 'Croat...","{'away_team_id': 782, 'away_team_name': 'Belgi...",0,0
3,3857274,2022-11-25,"{'home_team_id': 941, 'home_team_name': 'Nethe...","{'away_team_id': 3565, 'away_team_name': 'Ecua...",1,1
4,3857255,2022-12-01,"{'home_team_id': 778, 'home_team_name': 'Japan...","{'away_team_id': 772, 'away_team_name': 'Spain...",2,1

In [7]:
pd.json_normalize(matches["home_team"])

,home_team_id,home_team_name,home_team_gender,home_team_group,managers,country.id,country.name
0,1833,Canada,male,F,"[{'id': 4435, 'name': 'John Herdman', 'nicknam...",40,Canada
1,768,England,male,B,"[{'id': 277, 'name': 'Gareth Southgate', 'nick...",68,England
2,785,Croatia,male,F,"[{'id': 307, 'name': 'Zlatko Dalić', 'nickname...",56,Croatia
3,941,Netherlands,male,A,"[{'id': 788, 'name': 'Louis van Gaal', 'nickna...",160,Netherlands
4,778,Japan,male,E,"[{'id': 5699, 'name': 'Hajime Moriyasu', 'nick...",114,Japan
...,...,...,...,...,...,...,...
59,772,Spain,male,E,"[{'id': 793, 'name': 'Luis Enrique Martínez Ga...",214,Spain
60,785,Croatia,male,F,"[{'id': 307, 'name': 'Zlatko Dalić', 'nickname...",56,Croatia
61,2722,Cameroon,male,G,"[{'id': 1001250, 'name': 'Rigobert Song Bahana...",39,Cameroon
62,771,France,male,D,"[{'id': 545, 'name': 'Didier Deschamps', 'nick...",78,France
63,791,South Korea,male,H,"[{'id': 5688, 'name': 'Paulo Jorge Gomes Bento...",121,Korea (South)

In [8]:
events_url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/3857276.json"
events = pd.read_json(events_url)
events.shape

(3388, 38)

In [9]:
events["type_name"] = pd.json_normalize(events["type"])["name"]
events["type_name"].value_counts()

type_name
Pass                 955
Ball Receipt*        868
Carry                782
Pressure             289
Ball Recovery         93
Duel                  63
Clearance             41
Dribble               39
Miscontrol            32
Foul Committed        31
Foul Won              31
Block                 27
Dispossessed          23
Dribbled Past         23
Interception          23
Goal Keeper           16
Shot                  12
Substitution          10
Tactical Shift         5
Half Start             4
Half End               4
Injury Stoppage        4
Referee Ball-Drop      4
Starting XI            2
50/50                  2
Error                  1
Shield                 1
Own Goal For           1
Own Goal Against       1
Offside                1
Name: count, dtype: int64

In [10]:
shots = events[events["type_name"] == "Shot"]
shots.shape

(12, 39)

In [11]:
shots["shot"].iloc[0]

{'statsbomb_xg': 0.038882375000000004,
 'end_location': [104.1, 39.4],
 'key_pass_id': 'adb7af16-6e6c-4f23-a405-e9488608b93b',
 'technique': {'id': 93, 'name': 'Normal'},
 'body_part': {'id': 38, 'name': 'Left Foot'},
 'type': {'id': 87, 'name': 'Open Play'},
 'outcome': {'id': 96, 'name': 'Blocked'},
 'first_time': True,
 'freeze_frame': [{'location': [108.6, 34.8],
   'player': {'id': 9922, 'name': 'David Junior Hoilett'},
   'position': {'id': 19, 'name': 'Center Attacking Midfield'},
   'teammate': True},
  {'location': [112.7, 45.5],
   'player': {'id': 16459, 'name': 'Cyle Larin'},
   'position': {'id': 23, 'name': 'Center Forward'},
   'teammate': True},
  {'location': [108.6, 42.5],
   'player': {'id': 12770, 'name': 'Jonathan Osorio'},
   'position': {'id': 9, 'name': 'Right Defensive Midfield'},
   'teammate': True},
  {'location': [109.2, 27.6],
   'player': {'id': 24024, 'name': 'Tajon Buchanan'},
   'position': {'id': 16, 'name': 'Left Midfield'},
   'teammate': True},
  {'location': [94.4, 20.6],
   'player': {'id': 29758, 'name': 'Sam Adekugbe'},
   'position': {'id': 6, 'name': 'Left Back'},
   'teammate': True},
  {'location': [100.1, 49.5],
   'player': {'id': 12365, 'name': 'Alphonso Davies'},
   'position': {'id': 12, 'name': 'Right Midfield'},
   'teammate': True},
  {'location': [89.8, 57.6],
   'player': {'id': 44703, 'name': 'Alistair Johnston'},
   'position': {'id': 2, 'name': 'Right Back'},
   'teammate': True},
  {'location': [83.9, 46.1],
   'player': {'id': 11846, 'name': 'Steven de Sousa Vitoria'},
   'position': {'id': 3, 'name': 'Right Center Back'},
   'teammate': True},
  {'location': [108.3, 47.9],
   'player': {'id': 15890, 'name': 'Noussair Mazraoui'},
   'position': {'id': 6, 'name': 'Left Back'},
   'teammate': False},
  {'location': [112.5, 41.6],
   'player': {'id': 5234, 'name': 'Sofyan Amrabat'},
   'position': {'id': 10, 'name': 'Center Defensive Midfield'},
   'teammate': False},
  {'location': [102.2, 46.3],
   'player': {'id': 5219, 'name': 'Romain Saïss'},
   'position': {'id': 5, 'name': 'Left Center Back'},
   'teammate': False},
  {'location': [108.2, 36.6],
   'player': {'id': 12149, 'name': 'Nayef Aguerd'},
   'position': {'id': 3, 'name': 'Right Center Back'},
   'teammate': False},
  {'location': [108.9, 32.3],
   'player': {'id': 5245, 'name': 'Achraf Hakimi Mouh'},
   'position': {'id': 2, 'name': 'Right Back'},
   'teammate': False},
  {'location': [104.1, 39.3],
   'player': {'id': 46258, 'name': 'Azzedine Ounahi'},
   'position': {'id': 13, 'name': 'Right Center Midfield'},
   'teammate': False},
  {'location': [102.0, 43.2],
   'player': {'id': 3634, 'name': 'Abdelhamid Sabiri'},
   'position': {'id': 15, 'name': 'Left Center Midfield'},
   'teammate': False},
  {'location': [100.7, 52.2],
   'player': {'id': 3625, 'name': 'Sofiane Boufal'},
   'position': {'id': 21, 'name': 'Left Wing'},
   'teammate': False},
  {'location': [97.1, 38.4],
   'player': {'id': 5237, 'name': 'Hakim Ziyech'},
   'position': {'id': 17, 'name': 'Right Wing'},
   'teammate': False},
  {'location': [95.6, 41.2],
   'player': {'id': 6301, 'name': 'Youssef En-Nesyri'},
   'position': {'id': 23, 'name': 'Center Forward'},
   'teammate': False},
  {'location': [118.5, 39.1],
   'player': {'id': 6785, 'name': 'Yassine Bounou'},
   'position': {'id': 1, 'name': 'Goalkeeper'},
   'teammate': False}]}

In [12]:
shots_clean = pd.json_normalize(shots["shot"])
shots_clean[["statsbomb_xg", "body_part.name", "type.name", "outcome.name"]]

      statsbomb_xg body_part.name  type.name outcome.name
99        0.038882      Left Foot  Open Play      Blocked
202       0.024477      Left Foot  Open Play         Goal
297       0.022070     Right Foot  Free Kick      Blocked
305       0.061586      Left Foot  Open Play      Wayward
481       0.279145     Right Foot  Open Play        Off T
519       0.022624      Left Foot  Open Play        Off T
844       0.104058     Right Foot  Open Play         Goal
1188      0.097118     Right Foot  Open Play      Blocked
1640      0.094470     Right Foot  Open Play      Wayward
2273      0.051904      Left Foot  Open Play        Off T
2740      0.086874           Head  Open Play         Post
2744      0.638813           Head  Open Play        Off T

In [13]:
shots["location"].iloc[0]

[96.5, 40.7]

In [14]:
shots = events[events["type_name"] == "Shot"].copy()
shots["x"] = shots["location"].str[0]
shots["y"] = shots["location"].str[1]

shots[["x", "y"]]

          x     y
99     96.5  40.7
202    83.9  45.0
297    86.8  38.4
305   107.0  48.3
481   113.3  34.9
519    97.5  54.0
844   107.6  53.2
1188  107.9  34.2
1640  106.8  46.7
2273  105.1  41.2
2740  112.2  37.7
2744  118.8  41.6

In [15]:
import numpy as np

shots["distance"] = np.sqrt((120 - shots["x"])**2 + (40 - shots["y"])**2)

shots[["x", "y", "distance"]]

          x     y   distance
99     96.5  40.7  23.510423
202    83.9  45.0  36.444616
297    86.8  38.4  33.238532
305   107.0  48.3  15.423683
481   113.3  34.9   8.420214
519    97.5  54.0  26.500000
844   107.6  53.2  18.110770
1188  107.9  34.2  13.418271
1640  106.8  46.7  14.803040
2273  105.1  41.2  14.948244
2740  112.2  37.7   8.132035
2744  118.8  41.6   2.000000

In [16]:
shot_details = pd.json_normalize(shots["shot"])
shots["xg_statsbomb"] = shot_details["statsbomb_xg"]
shots["outcome"] = shot_details["outcome.name"]

shots[["distance", "xg_statsbomb", "outcome"]].sort_values("distance")

       distance  xg_statsbomb  outcome
2744   2.000000      0.638813    Off T
2740   8.132035      0.086874     Post
481    8.420214      0.279145    Off T
1188  13.418271      0.097118  Blocked
1640  14.803040      0.094470  Wayward
2273  14.948244      0.051904    Off T
305   15.423683      0.061586  Wayward
844   18.110770      0.104058     Goal
99    23.510423      0.038882  Blocked
519   26.500000      0.022624    Off T
297   33.238532      0.022070  Blocked
202   36.444616      0.024477     Goal

In [17]:
shots["xg_statsbomb"].sum()

np.float64(1.522021837)

In [18]:
match_ids = matches["match_id"].tolist()
len(match_ids)

64

In [20]:
def get_shots(match_id):
    url = f"https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/{match_id}.json"
    events = pd.read_json(url)
    events["type_name"] = pd.json_normalize(events["type"])["name"]
    shots = events[events["type_name"] == "Shot"].copy()
    shots["x"] = shots["location"].str[0]
    shots["y"] = shots["location"].str[1]
    shots["distance"] = np.sqrt((120 - shots["x"])**2 + (40 - shots["y"])**2)

    shot_details = pd.json_normalize(shots["shot"])
    shots["xg_statsbomb"] = shot_details["statsbomb_xg"]
    shots["outcome"] = shot_details["outcome.name"]

    shots["match_id"] = match_id
    return shots

In [21]:
test = get_shots(3857276)
test[["match_id", "distance", "xg_statsbomb", "outcome"]]

      match_id   distance  xg_statsbomb  outcome
99     3857276  23.510423      0.038882  Blocked
202    3857276  36.444616      0.024477     Goal
297    3857276  33.238532      0.022070  Blocked
305    3857276  15.423683      0.061586  Wayward
481    3857276   8.420214      0.279145    Off T
519    3857276  26.500000      0.022624    Off T
844    3857276  18.110770      0.104058     Goal
1188   3857276  13.418271      0.097118  Blocked
1640   3857276  14.803040      0.094470  Wayward
2273   3857276  14.948244      0.051904    Off T
2740   3857276   8.132035      0.086874     Post
2744   3857276   2.000000      0.638813    Off T

In [22]:
all_shots = []

for match_id in match_ids:
    print(match_id)
    all_shots.append(get_shots(match_id))

shots_all = pd.concat(all_shots, ignore_index=True)
shots_all.shape

3857276
3857271
3857296
3857274
3857255
3857272
3857278
3857277
3857273
3857275
3857261
3857290
3857298
3857285
3857282
3857297
3857294
3857266
3857284
3857254
3857265
3857301
3857268
3857269
3869321
3857292
3857295
3869685
3869684
3857256
3869151
3857257
3857258
3857288
3857267
3857287
3869486
3857260
3857264
3857289
3869254
3869118
3869519
3869354
3869552
3869420
3869220
3869219
3869253
3869152
3869117
3857270
3857263
3857259
3857283
3857286
3857300
3857299
3857293
3857291
3857281
3857280
3857279
3857262

(1494, 47)

In [23]:
shots_all["is_goal"] = (shots_all["outcome"] == "Goal").astype(int)
shots_all["is_goal"].mean()

np.float64(0.13052208835341367)

In [24]:
shots_all["is_goal"].sum()

np.int64(195)

In [25]:
shots_all["period"].value_counts()

period
2    801
1    607
5     41
4     25
3     20
Name: count, dtype: int64

In [26]:
shots_open = shots_all[shots_all["period"] != 5].copy()

print(shots_open.shape)
print(shots_open["is_goal"].sum())

(1453, 48)
169

In [27]:
shots_open["zone"] = pd.cut(
    shots_open["distance"],
    bins=[0, 6, 12, 18, 24, 30, 100],
    labels=["0-6", "6-12", "12-18", "18-24", "24-30", "30+"]
)

shots_open.groupby("zone", observed=True)["is_goal"].agg(["count", "mean"])

       count      mean
zone
0-6       50  0.440000
6-12     337  0.228487
12-18    366  0.125683
18-24    314  0.047771
24-30    258  0.023256
30+      128  0.023438

In [29]:
ux = 120 - shots_open["x"]
uy = 36 - shots_open["y"]

vx = 120 - shots_open["x"]
vy = 44 - shots_open["y"]

produit_scalaire = ux * vx + uy * vy
norme_u = np.sqrt(ux**2 + uy**2)
norme_v = np.sqrt(vx**2 + vy**2)

cos_angle = produit_scalaire / (norme_u * norme_v)
shots_open["angle"] = np.degrees(np.arccos(cos_angle))

In [30]:
shots_open[["x", "y", "distance", "angle", "xg_statsbomb"]].sort_values("angle", ascending=False).head(10)

          x     y  distance       angle  xg_statsbomb
85    118.7  40.2  1.315295  143.915371      0.872618
11    118.8  41.6  2.000000  141.340192      0.638813
326   117.6  40.3  2.418677  117.862983      0.688391
1359  118.0  42.7  3.360060  106.403111      0.711069
1258  118.5  43.2  3.534119  106.304198      0.894507
852   116.7  40.2  3.306055  100.871037      0.288100
59    117.4  37.3  3.748333   95.355825      0.572149
1473  116.7  38.0  3.858756   92.407609      0.624296
207   116.1  39.5  3.931921   90.991559      0.610025
417   117.4  37.0  3.969887   90.661076      0.271350

In [31]:
shots_open = shots_open.reset_index(drop=True)

details = pd.json_normalize(shots_open["shot"])

shots_open["shot_type"] = details["type.name"]
shots_open["body_part"] = details["body_part.name"]
shots_open["technique"] = details["technique.name"]

shots_open[["shot_type", "body_part", "technique"]].head()

   shot_type   body_part    technique
0  Open Play   Left Foot       Normal
1  Open Play   Left Foot          Lob
2  Free Kick  Right Foot       Normal
3  Open Play   Left Foot  Half Volley
4  Open Play  Right Foot  Half Volley

In [32]:
shots_open.groupby("shot_type", observed=True)["is_goal"].agg(["count", "mean"])

           count      mean
shot_type
Corner         2  0.000000
Free Kick     46  0.043478
Open Play   1382  0.108538
Penalty       23  0.739130

In [33]:
shots_model = shots_open[shots_open["shot_type"] != "Penalty"].copy()
shots_model.shape

(1430, 53)

In [34]:
shots_model["under_pressure"].value_counts(dropna=False)

under_pressure
NaN    1192
1.0     238
Name: count, dtype: int64

In [35]:
shots_model["under_pressure"] = shots_model["under_pressure"].fillna(0).astype(int)

features = pd.get_dummies(
    shots_model[["distance", "angle", "under_pressure", "body_part", "shot_type", "technique"]],
    columns=["body_part", "shot_type", "technique"],
    drop_first=True
)

print(features.shape)
features.head()

(1430, 14)

,distance,angle,under_pressure,body_part_Left Foot,body_part_Other,body_part_Right Foot,shot_type_Free Kick,shot_type_Open Play,technique_Diving Header,technique_Half Volley,technique_Lob,technique_Normal,technique_Overhead Kick,technique_Volley
0,23.510423,19.303454,1,True,False,False,False,True,False,False,False,True,False,False
1,36.444616,12.412158,0,True,False,False,False,True,False,False,True,False,False,False
2,33.238532,13.708899,0,False,False,True,True,False,False,False,False,True,False,False
3,15.423683,25.112519,0,True,False,False,False,True,False,True,False,False,False,False
4,8.420214,44.313540,0,False,False,True,False,True,False,True,False,False,False,False